# Generated by Django 3.2.8 on 2023-05-25 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUENTAS',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cuenta')),
                ('n_operaciones', models.CharField(max_length=100, null=True, verbose_name='Número de Operaciones')),
                ('operaciones_restantes', models.CharField(max_length=100, null=True, verbose_name='Operaciones restantes')),
                ('capital_riesgo', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Capital riesgo')),
                ('riesgo_operacion', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Riesgo por operación')),
                ('nivel_riesgo', models.CharField(max_length=100, null=True, verbose_name='Nivel de riesgo')),
                ('capital_actual', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Capital actual')),
                ('n_login', models.CharField(max_length=100, null=True, verbose_name='Login')),
                ('fecha_cuenta', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Cuenta')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comisión')),
                ('swap', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Swap')),
                ('broker', models.CharField(max_length=100, null=True, verbose_name='Broker')),
            ],
        ),
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=1000, null=True, verbose_name='Ingresa un Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TIPOCUENTA',
            fields=[
                ('id_tipo_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TRADES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.CharField(max_length=100, null=True, verbose_name='Activo')),
                ('orden', models.CharField(max_length=100, null=True, verbose_name='Orden')),
                ('stoploss', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Stoploss')),
                ('takeprofit', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Takeprofit')),
                ('lotaje', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Lotaje')),
                ('ratio', models.CharField(max_length=100, null=True, verbose_name='Ratio')),
                ('beneficio_esperado', models.CharField(max_length=100, null=True, verbose_name='Beneficio esperado')),
                ('utilidad_proyectada', models.CharField(max_length=100, null=True, verbose_name='Utilidad proyectada')),
                ('resultado', models.CharField(max_length=100, null=True, verbose_name='Resultado')),
                ('fecha', models.DateTimeField(max_length=10, null=True, verbose_name='Fecha')),
                ('beneficio_real', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Beneficio Real')),
                ('porcentaje_beneficio_real', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Beneficio Real')),
                ('id_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GRB.cuentas', verbose_name='Id Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='TRADEIMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRB.image')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRB.trades')),
            ],
        ),
        migrations.AddField(
            model_name='cuentas',
            name='id_tipo_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GRB.tipocuenta', verbose_name='Id tipo cuenta'),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
    ]
