# Generated by Django 3.2.8 on 2023-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0002_auto_20230507_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='beneficio_real',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='porcentaje_beneficio_real',
        ),
    ]
