# Generated by Django 3.2.8 on 2023-06-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0002_alter_cuentas_id_tipo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DESCUENTOS',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comisión')),
                ('swap', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Swap')),
                ('id_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GRB.cuentas', verbose_name='Id Cuenta')),
            ],
        ),
    ]
