# Generated by Django 3.2.8 on 2023-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0002_alter_trades_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='riesgo_operacion',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Riesgo por operación'),
        ),
    ]
