# Generated by Django 3.2.8 on 2023-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0003_auto_20230507_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='beneficio_real',
            field=models.CharField(max_length=100, null=True, verbose_name='Beneficio real'),
        ),
        migrations.AddField(
            model_name='trades',
            name='porcentaje_beneficio_real',
            field=models.CharField(max_length=100, null=True, verbose_name=' % Beneficio real'),
        ),
    ]
