# Generated by Django 3.2.8 on 2023-05-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0004_auto_20230507_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='beneficio_total',
            field=models.CharField(max_length=100, null=True, verbose_name='Beneficio Total'),
        ),
    ]
