# Generated by Django 3.2.8 on 2023-11-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0004_alter_cuentas_riesgo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='fecha_updated',
            field=models.DateTimeField(null=True, verbose_name='Fecha actualizada'),
        ),
    ]
