# Generated by Django 3.2.8 on 2023-06-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0004_auto_20230601_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comisión'),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='swap',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Swap'),
        ),
    ]
