# Generated by Django 3.2.8 on 2023-05-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0005_trades_beneficio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='beneficio_total',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='beneficio_total',
            field=models.CharField(max_length=100, null=True, verbose_name='Beneficio Total'),
        ),
    ]
