# Generated by Django 3.2.8 on 2023-12-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0005_trades_fecha_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
