# Generated by Django 3.2.8 on 2023-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0006_auto_20230508_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas',
            name='beneficio_total',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Capital actual'),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='swap',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Capital actual'),
        ),
    ]
