# Generated by Django 3.2.8 on 2023-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0007_auto_20230509_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comisión'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='swap',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Swap'),
        ),
    ]
