# Generated by Django 3.2.8 on 2023-06-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0007_auto_20230629_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas',
            name='riesgo_operacion',
        ),
    ]
