# Generated by Django 3.2.8 on 2023-06-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0008_remove_cuentas_riesgo_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='riesgo_operacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Nivel de riesgo'),
        ),
    ]
