# Generated by Django 3.2.8 on 2023-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0008_auto_20230509_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='beneficio_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Beneficio Real'),
        ),
    ]
