# Generated by Django 3.2.8 on 2023-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0009_alter_trades_beneficio_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='porcentaje_beneficio_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Beneficio Real'),
        ),
    ]
