# Generated by Django 3.2.8 on 2023-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0010_trades_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocuenta',
            name='id_tipo_cuenta',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=''),
        ),
    ]
