# Generated by Django 3.2.8 on 2023-07-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0012_alter_cuentas_n_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARCIALES',
            fields=[
                ('id_parciales', models.AutoField(primary_key=True, serialize=False)),
                ('parciales', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='parciales')),
            ],
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='broker',
            field=models.CharField(max_length=50, null=True, verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='n_operaciones',
            field=models.CharField(max_length=20, null=True, verbose_name='Número de Operaciones'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='nivel_riesgo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='operaciones_restantes',
            field=models.CharField(max_length=20, null=True, verbose_name='Operaciones restantes'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='resultado_cuenta',
            field=models.CharField(max_length=50, null=True, verbose_name='Selecciona una resultado'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='activo',
            field=models.CharField(max_length=6, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='orden',
            field=models.CharField(max_length=10, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='resultado',
            field=models.CharField(max_length=50, null=True, verbose_name='Resultado'),
        ),
        migrations.CreateModel(
            name='TRADEPARCIALES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parciales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRB.parciales')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRB.trades')),
            ],
        ),
    ]
