# Generated by Django 3.2.8 on 2023-07-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0015_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
