# Generated by Django 3.2.8 on 2023-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRB', '0017_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
