# Generated by Django 2.2.16 on 2023-03-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id_trade', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('stoploss', models.FloatField()),
                ('takeprofit', models.FloatField()),
                ('lotaje', models.FloatField(verbose_name=2)),
                ('ratio', models.CharField(max_length=100)),
                ('beneficio_esperado', models.CharField(max_length=100)),
                ('utilidad_proyectada', models.CharField(max_length=100)),
            ],
        ),
    ]
